apiVersion: v1
kind: Service
metadata:
  name: app-nodeport-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007

