---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app 
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccount: app-sa
      containers:
      - name: app
        image: kvad/app-aishima:0.4
        ports:
        - containerPort: 5000
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          runAsNonRoot: true

